### ISSUE TITLE
Fix texture map ?

### ISSUE THREAD

**Issue by Michaelwhite34** [abdallahdib/NextFace#14]
After exporting mesh and texture maps,can we edit the texture and run the program with the edited texture fixed?

**Comment by Michaelwhite34** [comment]
For example,there is a black area in the face caused by lighting,but the program put it into the diffuse texture.So we edit out the black area in the diffuse map and tell the program to use the edited map. Is this possible?

**Comment by abdallahdib** [comment]
> 
After exporting mesh and texture maps,can we edit the texture and run the program with the edited texture fixed?

This is possible but that mean u will have to modify pickle files saved in the checkpoints directory. this pickle file contains the optimized texture, u will have to read this pickle, replace the optimized texture with ur own one and run the optimization by adding the flag: --checkpoint PathToUrPickleFile. this will resume the optimization by initializing the variables with the one in the pickle file. 

> 
For example,there is a black area in the face caused by lighting,but the program put it into the diffuse texture.So we edit out the black area in the diffuse map and tell the program to use the edited map. Is this possible?

did u try to use the  optimConfigShadows.ini ? it is meant to handle challenging lighting conditions that regularize more the textures to avoid baking lighting in the maps but this trade-off details. it is worth to give it a try. for this, run the optim with the flag: --config  optimConfigShadows.ini 

plz refer to the readme.md as u may want to increase/reduce the  symmetry/consistency regularizers depending on how challenging the lighting conditions are in ur image. 

From the readme: 

he spherical harmonics can only model lights at infinity, under strong directional shadows, the estimated light may not be accurate as it can be, so residual shadows may appear in the estimated albedos. You can attenuate this by increasing the value of regularizers in the optimConfig.ini file, but this trade-off albedo details. Below are the values to modify:
for diffuse map: weightDiffuseSymmetryReg and weightDiffuseConsistencyReg,
for specular map: weightSpecularSymmetryReg, weightSpecularConsistencyReg
for roughness map: weightRoughnessSymmetryReg and weightRoughnessConsistencyReg I also provided a configuration file named optimConfigShadows.ini which have higher values for these regularizers that u can try.

**Comment by Michaelwhite34** [comment]
> > After exporting mesh and texture maps,can we edit the texture and run the program with the edited texture fixed?
> 
> This is possible but that mean u will have to modify pickle files saved in the checkpoints directory. this pickle file contains the optimized texture, u will have to read this pickle, replace the optimized texture with ur own one and run the optimization by adding the flag: --checkpoint PathToUrPickleFile. this will resume the optimization by initializing the variables with the one in the pickle file.
> 
> > For example,there is a black area in the face caused by lighting,but the program put it into the diffuse texture.So we edit out the black area in the diffuse map and tell the program to use the edited map. Is this possible?
> 
> did u try to use the optimConfigShadows.ini ? it is meant to handle challenging lighting conditions that regularize more the textures to avoid baking lighting in the maps but this trade-off details. it is worth to give it a try. for this, run the optim with the flag: --config optimConfigShadows.ini
> 
> plz refer to the readme.md as u may want to increase/reduce the symmetry/consistency regularizers depending on how challenging the lighting conditions are in ur image.
> 
> From the readme:
> 
> he spherical harmonics can only model lights at infinity, under strong directional shadows, the estimated light may not be accurate as it can be, so residual shadows may appear in the estimated albedos. You can attenuate this by increasing the value of regularizers in the optimConfig.ini file, but this trade-off albedo details. Below are the values to modify: for diffuse map: weightDiffuseSymmetryReg and weightDiffuseConsistencyReg, for specular map: weightSpecularSymmetryReg, weightSpecularConsistencyReg for roughness map: weightRoughnessSymmetryReg and weightRoughnessConsistencyReg I also provided a configuration file named optimConfigShadows.ini which have higher values for these regularizers that u can try.

Thanks I'll try it later.By the way the obj seems to have wrong scale when imported to blender.

**Comment by abdallahdib** [comment]
the obj is exported with the same scale of the statistical morphable model of basel. u can always change this scale

**Comment by Michaelwhite34** [comment]
> the obj is exported with the same scale of the statistical morphable model of basel. u can always change this scale

If I use stage 2 pickle file as checkpoint, It will start over from stage 1 and mess up with face geometry. I think you can add an argument to choose from resume current stage or start from next stage. Also for current stage, the number should be modified iter step number - original step, if 0 or negative, continue from next stage.But to do that maybe you need to export map before stage 3 ?

**Comment by Michaelwhite34** [comment]
> > After exporting mesh and texture maps,can we edit the texture and run the program with the edited texture fixed?
> 
> This is possible but that mean u will have to modify pickle files saved in the checkpoints directory. this pickle file contains the optimized texture, u will have to read this pickle, replace the optimized texture with ur own one and run the optimization by adding the flag: --checkpoint PathToUrPickleFile. this will resume the optimization by initializing the variables with the one in the pickle file.
> 
> > For example,there is a black area in the face caused by lighting,but the program put it into the diffuse texture.So we edit out the black area in the diffuse map and tell the program to use the edited map. Is this possible?
> 
> did u try to use the optimConfigShadows.ini ? it is meant to handle challenging lighting conditions that regularize more the textures to avoid baking lighting in the maps but this trade-off details. it is worth to give it a try. for this, run the optim with the flag: --config optimConfigShadows.ini
> 
> plz refer to the readme.md as u may want to increase/reduce the symmetry/consistency regularizers depending on how challenging the lighting conditions are in ur image.
> 
> From the readme:
> 
> he spherical harmonics can only model lights at infinity, under strong directional shadows, the estimated light may not be accurate as it can be, so residual shadows may appear in the estimated albedos. You can attenuate this by increasing the value of regularizers in the optimConfig.ini file, but this trade-off albedo details. Below are the values to modify: for diffuse map: weightDiffuseSymmetryReg and weightDiffuseConsistencyReg, for specular map: weightSpecularSymmetryReg, weightSpecularConsistencyReg for roughness map: weightRoughnessSymmetryReg and weightRoughnessConsistencyReg I also provided a configuration file named optimConfigShadows.ini which have higher values for these regularizers that u can try.

If I use stage 2 pickle file as checkpoint, It will start over from stage 1 and mess up with face geometry. I think you can add an argument to choose from resume current stage or start from next stage. Also for current stage, the number should be modified iter step number - original step, if 0 or negative, continue from next stage.But to do that maybe you need to export map before stage 3 ?
