### ISSUE TITLE
BRDF lighting

### ISSUE THREAD

**Issue by jiaxiangshang** [abdallahdib/NextFace#23]
Hi abdallah,

NextFace result is amazing, while I meet some problems in the brdf formulation. 
In paper, you say the roughness is static, and I see u put it as 0.4 https://github.com/abdallahdib/NextFace/blob/72a0b08ad7451766408967bcd153bed0d4cac604/pipeline.py#L59

May I know, why do this or why this work?

Best
Jiaxiang

**Comment by abdallahdib** [comment]
Hi and sorry for my late response, 
In the second stage of the code, we rely on statistical albedo priors (specular and diffuse) to obtain a first estimation. because we do not have statistical prior for the roughness, we used  a constant term (0.4) which is a good approximation for face skin. this value is then refined in the third stage. reducing the roughness term results in shiny (plastic face) u can try and see it by yourself. values between [0.2, 0.4] are good approximation for face skin.

**Comment by jiaxiangshang** [comment]
Oh, thanks you for your reply, I got it and I will have a try.

**Comment by abdallahdib** [comment]
great and good luck and let me know if u have other questions :)
