### ISSUE TITLE
CUDA Runtime Error: operation not supported at /tmp/pip-req-build-mjlbq5xq/src/buffer.h:55

### ISSUE THREAD

**Issue by haoxurt** [abdallahdib/NextFace#3]
In the second step, it will occur this problem?  How can I solve it?   My torch version is 1.3.1 and CUDA version is 10.1.

**Comment by abdallahdib** [comment]
that looks weird, can u tell at which line it is happening? 

plz try this simple pytorch example so to verify that ur installation is fine, something like this:
import torch
torch.tensor([0]).cuda()

**Comment by haoxurt** [comment]
> that looks weird, can u tell at which line it is happening?
> 
> plz try this simple pytorch example so to verify that ur installation is fine, something like this: import torch torch.tensor([0]).cuda()

It shows 'tensor([0], device='cuda:0')'. The cuda is no problem.  My system is centos7.0.

**Comment by haoxurt** [comment]
It happened when run  'pyredner.RenderFunction.apply'  in the rayTrace function.

**Comment by abdallahdib** [comment]
okay its related to redner. 
does this script runs on ur pc:
https://github.com/BachiLi/redner/blob/master/tests/test_single_triangle.py

**Comment by haoxurt** [comment]
No. It occured same problem.  It should be resulted by cuda version or  torch version .

**Comment by abdallahdib** [comment]
Ok the problem is redner not running correctly on ur centos.. as fallback please try on cpu ( set device to cpu in optimConfig.ini) this will be slower. Meantime try to uninstall redner with pip and install it again. I remember that i was able to run on centos so i dont see a reason for not having gpu in ur case. Maybe start again with a clean conda env/ check ur cuda drivers…

**Comment by haoxurt** [comment]
Ok, I can run successfully in the mode of cpu.
